### ISSUE TITLE
Bot crashes whenever it receives an emoji as reaction

### ISSUE THREAD

**Issue by shavitush** [Rapptz/discord.py#2422]
### Summary

The bot crashes whenever it receives an emoji as reaction.

### Reproduction Steps

Simply reacted to it with an :eyes: emoji in a DM

https://streamable.com/z4jbv

### Expected Results

The bot to not crash..?

### Actual Results

From what it seems, the traceback doesn't really show anything from my code so it's likely from the library itself

```
Traceback (most recent call last):
  File "main.py", line 363, in <module>
    client.run(config.get("discord", "token"))
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/home/shavit/.local/lib/python3.7/site-packages/discord/state.py", line 435, in parse_message_reaction_remove
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

```
shavit@windia:~/discord$ python3 -m discord -v
- Python v3.7.3-final
- discord.py v1.2.4-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019
```

**Comment by TheRockettek** [comment]
Update your discordpy version to the current master on github.

**Comment by samclane** [comment]
@TheRockettek Updated to `v1.3.0a`. Still gives me the same animated emoji error.

**Comment by Harmon758** [comment]
This should now be fixed with v1.2.5.
In the future, please make sure you're using the latest development version when reporting issues.

**Comment by vr6syncro** [comment]
Hey, updated my discord.py but bot still crash:

`Traceback (most recent call last):
  File "voicecreate.py", line 39, in <module>
    bot.run(DISCORD_TOKEN)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.7/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/usr/local/lib/python3.7/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/usr/local/lib/python3.7/site-packages/discord/state.py", line 407, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
root@Squad:/home/alex/VoiceCreateBot# python3 -m discord -v
- Python v3.7.3-final
- discord.py v1.2.5-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)
`

**Comment by zomatree** [comment]
your bot is not running on discord.py 1.2.5 please make sure you install discord.py and run the bot on the same python version.

**Comment by AdriRayns** [comment]
I can confirm that it is fixed.  I was getting erros in 1.2.4 until I upgraded to 1.2.5 discord.py version.

**Comment by Indiana3714** [comment]
1.2.5 has this issue still

**Comment by Indiana3714** [comment]
Even the latest git version of discord.py-1.3.0a2204+g87f9dcf  still crashes. The problem is NOT fixed at all unlike what is claimed

**Comment by skyblockz** [comment]
> Even the latest git version of discord.py-1.3.0a2204+g87f9dcf still crashes. The problem is NOT fixed at all unlike what is claimed

Post the logs instead of blaming

**Comment by Rapptz** [comment]
This issue is definitely fixed -- otherwise I'd be seeing more people complaining about it. Chances are you have an environment issue somewhere such as using mixed interpreters and virtual environments. Double check them to make sure.
