### ISSUE TITLE
ERROR: Exception: Traceback.

### ISSUE THREAD

**Issue by Kuhitacop** [Rapptz/discord.py#923]
Hello I get this errors...

https://gyazo.com/ed0522749bbbef6dd8ebbc32df860a07

**Comment by Rapptz** [comment]
This issue has nothing to do with this library. Looks like a `pip` issue. Try setting `chcp 65001` before running `pip` and see if it makes a difference.

**Comment by Gorialis** [comment]
This looks like the bug introduced by the new encoding standards set in Python 3.6 causing non-UTF8-compatible locales to break with `pip` enforcing UTF8.
If changing codepage doesn't work, I'd recommend trying to update `pip` first (`pip install -U pip`), and if that fails, installing a newer version (Python 3.6.2 or greater) should fix this issue.

**Comment by Kuhitacop** [comment]
Hello, thanks for your help!
Now the error changes, I'm getting this problem:
https://gyazo.com/ed2bcb3134c3a6c5f8a77d69395b5e73

**Comment by Gorialis** [comment]
This error is to do with the `request` library you're trying to install. I'm going to guess that you actually want `requests` (the `request` listing on PyPI looks like it might be attempting to squat `requests`), a HTTP(S) request library, so changing to `requests` in your pip command should fix your issue.

As an extra comment on the `requests` library, it is synchronous, which means it doesn't play nice with discord.py, an asyncio library (`requests` will block the event loop while performing any request).
I'd take a look at [What does "blocking" mean?](http://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean) and the documentation for the [aiohttp](https://aiohttp.readthedocs.io/en/stable/) library included with discord.py regarding performing asyncio-friendly HTTP requests.

**Comment by Kuhitacop** [comment]
Now I'm getting again this error:
https://gyazo.com/bf38a701d2acf18db97b8be1d2861424

What did you mean by changing codepage?

**Comment by Gorialis** [comment]
Changing codepage is done by the `chcp 65001` command (you already do it in your screenshot).

This still looks like the issue you were having before with encodings. This first appeared in 3.6.0a, and was fixed sometime between then and the latest version, 3.6.3 (you can use `py -3 -V` to check the version you're running).

If you're using one of the versions affected I'd suggest installing the latest version, or, if you already have, ensuring that the correct version is being used (consider adding `python` to PATH in the installer or configuring PATH yourself)

**Comment by Kuhitacop** [comment]
I'm running cmd as admin, I've set environment variables to path as python cmd is working in cmd.

Running from system32 folder:
https://gyazo.com/c03b309ce66b8611eea2e2c2267e64f5

Running from the bot folder:
https://gyazo.com/9bfbbe0b3bfe773c7ebb1d5cb2865cce

Running from the bot folder changing requests to request
https://gyazo.com/610c9c2b250962b17b528d51eca76fb6

Changing codepage to chcp 65001
https://gyazo.com/a1e67522706a0643a102bdc17f76eb2a

Python version:
https://gyazo.com/a03549ede935c1d49ac9aeddd74557f2

Any ideas?? I'm good in C and Visual Basic but never used Python and this shitty environments :S
Thanks brothers!

**Comment by Gorialis** [comment]
My only remaining guess for this is that for some reason an old `pip` version from 3.6.1 or etc is lingering in your new install. Try uninstalling all versions of Python and reinstalling **just** 3.6.3.

**Comment by Kuhitacop** [comment]
Done and I have the same error :S
https://gyazo.com/6a312c318502ec027d306f144431572c

**Comment by Gorialis** [comment]
I still have a feeling you have lingering data (pip is using cached packages in the screenshot).

Try:
- Uninstalling all versions of Python via Add/Remove Programs, etc.
- Deleting the `Python` folder in `C:\Program Files (x86)` (and `C:\Program Files` if there is one)
- Deleting the `Python` folder in `C:\Users\<username>\AppData\Roaming`
- Deleting the `pip` folder in `C:\Users\<username>\AppData\Local`
- Reinstalling 3.6.3 again through a fresh download (don't use an old installer)

If these steps don't fix the problem then 3.6.3 might be incompatible with your locale, making this a problem for the CPython developers to figure out.

**Comment by MysterialPy** [comment]
**Open a Command Prompt as an Administrator**

Determine what versions of Python you have:
`py -0`

If you have a 64-bit **AND** 32-bit architecture installed on 3.6, run these commands for the **32 bit version**:
(If not, remove the **-32**)
`py -3.6-32 -m pip install -U pip`
**Then:**
`py -3.6-32 -m pip install -U https://github.com/pypa/pip/archive/master.zip`

**_This will install the latest development version of `pip`._**

Now try install your packages in the same format, e.g:
`py -3.6-32 -m pip install -U ...`

If that doesn't fix your problem I would suggest doing what @Gorialis has said.

**Comment by Kuhitacop** [comment]
Hello I think I didn't understand some steps...
This is the result of cmd python -O
https://gyazo.com/c792a81e21bb60ab3c0d7d499b444ee7

What should I do now?
CMDS: py not working, python working!

**Comment by MysterialPy** [comment]
`py -0` not `O`

Anyways it seems this may be a feature not available on some Python Launchers so if it doesn't work, just ignore that step, and remove the `-32` bit from the other steps...

**Comment by Kuhitacop** [comment]
I did -0 and said incorrect command, that's why I made -O because I didn't get errors.

I didn't understand you: "If you have a 64-bit AND 32-bit architecture installed on 3.6, run these commands for the 32 bit version:
(If not, remove the -32)"

My computer is x64.

py -3.6-32 -m pip install -U pip
Then:
py -3.6-32 -m pip install -U https://github.com/pypa/pip/archive/master.zip

I run both or only 1 command?

I've installed Python x32 bits as x64 made me trouble (I was not able to see the Windows Forms correctly, most of them were blank)...

Thanks!!! <3<3<3

**Comment by MysterialPy** [comment]
`py -0` works on newer Python Launchers. AS I said, if it doesn't work just disregard.

As for the other steps, I thought it was pretty simple.

Run the commands for the 32 bit version of Python. IF you are unsure which version you have or only have one of 32/64 bit versions, don't include `-32` in your commands.

**So all you had to do was run:**
`py -3.6 -m pip install -U pip`
**Then run:**
`py -3.6 -m pip install -U https://github.com/pypa/pip/archive/master.zip`

_Then try and install your packages in the same format._
**For example:**
`py -3.6 -m pip install -U discord.py`

**Comment by Kuhitacop** [comment]
Thanks! Solved it! <3

> "If this fails well GoodLuck!" 
XDDD that was funny
